# Generated by Django 5.1.3 on 2025-01-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodmenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(blank=True, max_length=20, null=True)),
                ('foodtype', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodorderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderitemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('MENUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.foodmenutable')),
                ('ORDERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.foodordertable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='foodmenutable',
            name='RESTAURANTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.restauranttable'),
        ),
        migrations.CreateModel(
            name='RoomComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('roomtype', models.CharField(blank=True, max_length=20, null=True)),
                ('bedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('roomservice', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('checkindate', models.DateField(blank=True, null=True)),
                ('checkoutdate', models.DateField(blank=True, null=True)),
                ('paymentmethod', models.CharField(blank=True, max_length=20, null=True)),
                ('ROOMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.roomtable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('transactiontype', models.CharField(blank=True, max_length=20, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='foodordertable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable'),
        ),
        migrations.CreateModel(
            name='FeedbackTableforRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('ROOMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.roomtable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTableforRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('RESTAURANTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.restauranttable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOOKINGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.bookingtable')),
                ('ORDERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.orderitemtable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable'),
        ),
        migrations.CreateModel(
            name='WalletTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.FloatField(blank=True, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
    ]
