# Generated by Django 5.1.3 on 2025-01-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtable',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtable',
            name='roomimage',
            field=models.FileField(blank=True, null=True, upload_to='roomimages/'),
        ),
    ]
