# Generated by Django 5.1.3 on 2025-01-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0002_roomtable_location_roomtable_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktableforrestaurant',
            name='MENUID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.foodmenutable'),
        ),
        migrations.AlterField(
            model_name='feedbacktableforrestaurant',
            name='RESTAURANTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.restauranttable'),
        ),
    ]
