# Generated by Django 5.1.3 on 2024-12-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0002_logintable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='roomtable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable'),
        ),
    ]
