# Generated by Django 5.1.3 on 2025-01-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0003_feedbacktableforrestaurant_menuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemtable',
            name='ORDERID',
        ),
        migrations.AddField(
            model_name='foodordertable',
            name='ORDERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.orderitemtable'),
        ),
        migrations.AlterField(
            model_name='foodordertable',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='world_wallet_expence_app.logintable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='world_wallet_expence_app.usertable')),
            ],
        ),
    ]
