# Generated by Django 5.1.3 on 2024-12-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0003_usertable_status_alter_roomtable_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomprofileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantname', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
    ]
