# Generated by Django 5.1.3 on 2024-12-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0004_roomprofiletable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomprofileTable',
        ),
    ]
