# Generated by Django 5.1.3 on 2025-01-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0004_remove_orderitemtable_orderid_foodordertable_orderid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedVehicleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicletype', models.CharField(blank=True, max_length=50, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('placename', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('ticket_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
