# Generated by Django 5.1.3 on 2025-01-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0006_roomtable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
