# Generated by Django 5.1.3 on 2024-12-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0007_roomtable_roomservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtable',
            old_name='type',
            new_name='bedtype',
        ),
        migrations.AddField(
            model_name='roomtable',
            name='roomtype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
