# Generated by Django 5.1.3 on 2024-12-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0008_rename_type_roomtable_bedtype_roomtable_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='paymentmethod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
