# Generated by Django 5.1.3 on 2025-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0008_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
