# Generated by Django 5.1.3 on 2024-12-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0009_bookingtable_paymentmethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintTable',
            new_name='RestaurantComplaintTable',
        ),
        migrations.CreateModel(
            name='RoomComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.usertable')),
            ],
        ),
    ]
