# Generated by Django 5.1.3 on 2025-01-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0009_chathistory_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='session_id',
        ),
    ]
