# Generated by Django 5.1.3 on 2024-12-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0010_rename_complainttable_restaurantcomplainttable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordertable',
            name='RESTAURANTID',
        ),
    ]
