# Generated by Django 5.1.3 on 2025-01-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0010_remove_chathistory_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_query',
            field=models.CharField(max_length=255),
        ),
    ]
