# Generated by Django 5.1.3 on 2025-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0011_chathistory_session_id_alter_chathistory_user_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_query',
            field=models.TextField(),
        ),
    ]
