# Generated by Django 5.1.3 on 2025-01-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0014_remove_chathistory_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('chatbot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world_wallet_expence_app.logintable')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
