# Generated by Django 5.1.3 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0015_chat_history_delete_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordertable',
            name='ORDERID',
        ),
        migrations.AddField(
            model_name='foodordertable',
            name='ORDERID',
            field=models.ManyToManyField(to='world_wallet_expence_app.orderitemtable'),
        ),
    ]
