# Generated by Django 5.1.3 on 2025-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0016_remove_foodordertable_orderid_foodordertable_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcomplainttable',
            name='LOGINID',
        ),
        migrations.AddField(
            model_name='feedbacktableforrestaurant',
            name='reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktableforroom',
            name='reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='RestaurantComplaintTable',
        ),
        migrations.DeleteModel(
            name='RoomComplaintTable',
        ),
    ]
