# Generated by Django 5.1.3 on 2025-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0019_alter_logintable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenutable',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenutable',
            name='foodname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
