# Generated by Django 5.1.3 on 2025-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_wallet_expence_app', '0020_alter_foodmenutable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtable',
            name='roomservice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
